name = "zrzrzr"
main = "./index.html"
compatibility_date = "2024-07-02"
node_compat = true

[site]
bucket = "./"

[[rules]]
globs = ["**/*"]
headers = { 
  "Cache-Control" = "public, max-age=14400",
  "Content-Type" = "auto" 
}

[build]
command = "echo 'No build required'"
