name = "zrzrzr"
main = "./index.html"  # Главная точка входа
compatibility_date = "2024-07-02"
node_compat = true    # Включить совместимость с Node.js

[site]
bucket = "./"         # Корневая директория проекта

# Правила для статических файлов
[[rules]]
globs = ["**/*"]
headers = { 
  "Cache-Control" = "public, max-age=14400",
  "Content-Type" = { "html" = "text/html", "css" = "text/css", "js" = "application/javascript" }
}

[build]
command = "echo 'Static site, no build needed'"
